### ISSUE TITLE
can not find "mnist/model/model.cnn"

### ISSUE THREAD

**Issue by gogotanc** [DeepCompute/cnn#4]
```
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: mnist/model/model.cnn (没有那个文件或目录)
    at info.hb.cnn.core.CNN.saveModel(CNN.java:571)
    at info.hb.ccn.main.CNNMnist.runTrain(CNNMnist.java:45)
    at info.hb.ccn.main.CNNMnist.main(CNNMnist.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.FileNotFoundException: mnist/model/model.cnn (没有那个文件或目录)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
    at info.hb.cnn.core.CNN.saveModel(CNN.java:566)
    ... 7 more
```

没有 mnist/model/model.cnn 这个文件哒，要怎么获取呢？

**Comment by gogotanc** [comment]
还是说直接用 speech 下面那个就行。

**Comment by sajian** [comment]
You can create a folder named "model" under mnist/, then this execuption could be solved.
